### ISSUE TITLE
SARIF results don't show up when VS Code is open as administrator

### ISSUE THREAD

**Issue by sherryyshi** [microsoft/sarif-vscode-extension#394] opened 2021-08-18 18:08 UTC
Repro steps:
* Open new VS Code window as administrator
* Open a .sarif file

Expected:
* Sarif results show up

Actual:
* Sarif results tab shows up but is empty.

**Comment by michaelcfanning** [comment] 2021-08-18 18:17
@jeffersonking, do you have time to look at this? seems important.

**Comment by jeffersonking** [comment] 2021-08-20 07:47
@sherryyshi I am unable to reproduce the issue. I followed the steps and the results showed up. If you have a demo of the repro, I'd be happy to see it.

**Comment by sherryyshi** [comment] 2021-08-20 16:32
Sent over email :)

**Comment by jeffersonking** [comment] 2021-11-23 22:58
It is possible that #412 (v3.1.1) fixed this. Optimistically closing. @sherryyshi if you still see this issue can you reopen? Thanks!

**Closed by jeffersonking** 2021-11-23 22:58 UTC
