### ISSUE TITLE
Results pane never opens on extremely large directories

### ISSUE THREAD

**Issue by fwingerter-Ocient** [microsoft/sarif-vscode-extension#367] opened 2020-11-24 19:00 UTC
I'm attempting to use the SARIF viewer extension with a project that vendors a large number of dependencies. These dependencies and their build artifacts are in the workspace's `files.ignore` globs, so they do not slow down normal VS Code operation.

However, unless I delete these files (on the order of 300,000) or move them outside of my project directory, when opening a `.sarif` file, the SARIF Viewer extension never opens the results pane. Manually running the "open results pane" or "clear state" commands from the extension appears to do nothing.

After I delete or remove the subdirectories containing these dependencies, the SARIF viewer behaves normally.

My guess is that [index.ts:36](https://github.com/microsoft/sarif-vscode-extension/blob/master/src/extension/index.ts#L36) is taking effectively forever, and making the extension examine many more files than it should:

```const urisNonSarif = await workspace.findFiles('**/*', '.sarif');```

Because the extension passes a second [argument to `findFiles`](https://code.visualstudio.com/api/references/vscode-api#workspace.findFiles), the workspace `files.ignore` setting is [not respected](https://github.com/microsoft/vscode/issues/48674).

Presumably it would fix this issue to simply pass one argument to `findFiles` and then remove `.sarif` entries afterward. I'm not familiar with TypeScript or the VS Code extension development workflow, so it isn't easy for me to attempt a fix, but I could try if necessary.

**Comment by jeffersonking** [comment] 2020-11-25 00:32
I don't see a `files.ignore`. Did you mean `files.exclude`?

I just tested and `files.exclude` is being respected. My experience seems to be confirmed here: https://github.com/microsoft/vscode/issues/48674#issuecomment-384477494.

I will continue to look for other explanations for why these excluded files are causing a performance issue and try to reproduce it locally.

**Comment by fwingerter-Ocient** [comment] 2020-11-30 17:17
I did mean `files.exclude`. I also looked further into this, and it seems that I was mistaken--`files.exclude` is respected, but our repo also includes a large number of files not excluded. Nonetheless, it would be helpful to have a diagnostic for this situation as the behavior we experience is not trivial to debug--the extension just (visibly) does nothing.

**Comment by fwingerter-Ocient** [comment] 2020-12-02 22:42
Another symptom: when the results panel won't open due to too many files in the directory, saving files also hangs; the saving notification spins indefinitely until cancelled. However, hitting save again immediately after cancelling the notification does work. This spin-cancel-retry behavior on save occurs for all files in the window. Disabling SARIF Viewer makes saving work normally again.

**Comment by jeffersonking** [comment] 2020-12-02 22:44
That's very interesting. Thanks for sharing that.

**Comment by jeffersonking** [comment] 2021-11-23 23:07
@fwingerter-Ocient Thanks for your patience. #409 is likely to have addressed this issue. Optimistically closing. If not, we'd be happy to take another look.

**Closed by jeffersonking** 2021-11-23 23:07 UTC
