### ISSUE TITLE
Line numbers are off by one

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-vscode-extension#300] opened 2020-07-13 16:35 UTC
Here is a SARIF file with a single result on line 16:

[off-by-one.sarif.txt](https://github.com/microsoft/sarif-vscode-extension/files/4913792/off-by-one.sarif.txt)

But the VS Code extension shows it on line 15:

<img width="686" alt="off-by-one" src="https://user-images.githubusercontent.com/11762653/87329555-fc736100-c4eb-11ea-847a-623c06d6d788.png">

This is version 3.2020.629001-insiders:

<img width="281" alt="off-by-one-version" src="https://user-images.githubusercontent.com/11762653/87329696-33e20d80-c4ec-11ea-8d68-209e90c2ff49.png">

**Comment by jeffersonking** [comment] 2020-07-13 16:59
Duplicate of #295.

**Closed by jeffersonking** 2020-07-13 16:59 UTC
Labels: bug
